// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAOPIdV9aEi-3ZLYCI9ermniXLZWlu6Wo',
    appId: '1:80345836163:web:6a2ef067fe4a724d8b49b6',
    messagingSenderId: '80345836163',
    projectId: 'food-7fd95',
    authDomain: 'food-7fd95.firebaseapp.com',
    storageBucket: 'food-7fd95.firebasestorage.app',
    measurementId: 'G-HCL663MGTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3lIW2bvL3rWyHvsBmiw8wmZmgLfBOdWA',
    appId: '1:80345836163:android:5940cd4774bd91f08b49b6',
    messagingSenderId: '80345836163',
    projectId: 'food-7fd95',
    storageBucket: 'food-7fd95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbCVkR-vSZTVQvbBuLE-Eda4ekFpl617c',
    appId: '1:80345836163:ios:d24a360d68a79d088b49b6',
    messagingSenderId: '80345836163',
    projectId: 'food-7fd95',
    storageBucket: 'food-7fd95.firebasestorage.app',
    iosBundleId: 'com.example.stateBrainerAvr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbCVkR-vSZTVQvbBuLE-Eda4ekFpl617c',
    appId: '1:80345836163:ios:d24a360d68a79d088b49b6',
    messagingSenderId: '80345836163',
    projectId: 'food-7fd95',
    storageBucket: 'food-7fd95.firebasestorage.app',
    iosBundleId: 'com.example.stateBrainerAvr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAOPIdV9aEi-3ZLYCI9ermniXLZWlu6Wo',
    appId: '1:80345836163:web:4cf512b6416e5a0b8b49b6',
    messagingSenderId: '80345836163',
    projectId: 'food-7fd95',
    authDomain: 'food-7fd95.firebaseapp.com',
    storageBucket: 'food-7fd95.firebasestorage.app',
    measurementId: 'G-XSPK341BKG',
  );
}
